server:
  port: 8080
  servlet:
    context-path: /quiz-app

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/quiz_app'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "3w0z35vno+VFtyLNkyX9dCKYIkfX8CFJcFoExDX73rPOl5dl7GsCnHQru/84zKk6"